pre-commit:
  parallel: true
  commands:
    fmt:
      run: deno fmt --check {staged_files}
    lint:
      run: deno task lint:staged
    check:
      run: deno task check
    protected-dirs:
      run: deno run -A scripts/git-hooks/check-protected-dirs.ts
