// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/callback.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/login.tsx";
import * as $4 from "./routes/protected.tsx";
import * as $5 from "./routes/account.tsx";
import * as $i0 from "./islands/ProfileForm.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/callback.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/login.tsx": $3,
    "./routes/protected.tsx": $4,
    "./routes/account.tsx": $5,
  },
  islands: {
    "./islands/ProfileForm.tsx": $i0,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;