name: Commit Message Lint
on:
  push:
    branches: ["**"]
    paths-ignore: ["CHANGELOG.md"]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with: { fetch-depth: 0 }
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5.4.4
        with:
          configFile: .commitlintrc.json
