name: Coverage

on:
  push:
    branches:
      - "main"
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: v1.x

      - name: Cache Deno directory
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json') }}

      - name: Run Tests with Coverage
        run: |
          deno task coverage

      - name: Check Coverage Threshold (80%)
        run: |
          deno run -A scripts/coverage-threshold.ts 80

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./coverage.lcov
          fail_ci_if_error: true
