name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy SDK
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: v1.x

      - name: Bundle SDK
        run: deno task bundle:sdk

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "workos-sdk"
          entrypoint: "./dist/workos.js"
          root: "."
          import-map: "./deno.json"

      - name: Test module
        run: |
          echo "Testing WorkOS SDK deployment..."
          deno eval "import { WorkOS } from 'https://deno.land/x/workos-sdk/mod.ts'; console.log('WorkOS SDK loaded successfully');"
