name: Publish to JSR
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for JSR provenance

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: 2.x

      - name: Cache dependencies
        run: deno cache

      - name: Run tests
        run: deno task test

      - name: Publish to JSR.io
        run: deno run -A https://jsr.io/cli.ts publish
