name: Release & Publish

# A)  Every merge to main is inspected by Release-Please.
# B)  A tag created by Release-Please triggers the publish job.

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: write # create tags & release PRs
  pull-requests: write # open the release PR
  id-token: write # OIDC token for jsr publish (needed only in publish job)

jobs:
  release-please:
    if: github.event_name == 'push' && github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # ✨ provides the OIDC token for JSR
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno 2
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Run CI checks
        run: deno task ci-check

      # jsr publish automatically detects OIDC and prompts nothing.
      - name: Publish to JSR
        run: npx jsr publish
