name: Release
on:
  push:
    tags: [ "sdk-*.*.*" ]     # eg sdk-0.1.0-alpha.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: denoland/setup-deno@v2.0.2
        with: { deno-version: "2.x" }

      - name: Publish core SDK
        run: |
          cd packages/workos_sdk
          deno publish --allow-net

      - name: Publish Fresh helpers
        run: |
          cd ../../packages/workos_fresh
          deno publish --allow-net
