name: Test Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["2.x"]
        fresh: ["1.6.5", "2.0.0-rc.1"]
      # Don't cancel all jobs if one fails
      fail-fast: false

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ matrix.deno }}-${{ hashFiles('**/deno.json', '**/import_map.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-${{ matrix.deno }}-

      - name: Set Fresh version
        run: |
          echo "Setting Fresh version to ${{ matrix.fresh }}"
          if [[ "${{ matrix.fresh }}" == "1.6.5" ]]; then
            cp import_map.f1.json import_map.json
          else
            cp import_map.f2.json import_map.json
          fi

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        # Use --no-check for test execution since we have type errors
        run: deno check --no-lock $(find . -name '*.ts')

      - name: Cache Dependencies
        run: deno cache mod.ts

      - name: Run tests
        run: deno task test

      - name: Test Fresh example
        run: |
          cd examples/fresh-canary
          deno task check --no-check
          # Just verify it builds, don't actually run it
          deno check --no-check main.ts
